name:                helloworld
version:             0.1.0.0
github:              "githubuser/helloworld"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/helloworld#readme>

ghc-options:
  - -Wall -fno-warn-redundant-constraints

default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - TypeFamilies
  - TypeApplications
  - DataKinds
  - DeriveGeneric
  - GADTs
  - FlexibleContexts
  - FlexibleInstances
  - StandaloneDeriving
  - TypeSynonymInstances
  - PartialTypeSignatures

dependencies:
- base >= 4.7 && < 5
- beam-core
- beam-migrate
- beam-postgres
- postgresql-simple
- aeson 
- text
- websockets
- network
- transformers
- mtl
- amqp
- bytestring
- syb
- graphql-meta
- protolude
- raw-strings-qq
- scotty
- uuid
- hasql
- contravariant
- retry

library:
  source-dirs: 
  - src
  other-modules:
  - Modules.Organization.SchemaSQL
  - Modules.Organization.Schema
  
executables:
  helloworld-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - helloworld

tests:
  helloworld-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - helloworld
